game_result = [
    { 'round': 1, 'name': 'JD', 'score': -10 },
    { 'round': 1, 'name': 'YE', 'score': 20 },
    { 'round': 1, 'name': 'HW', 'score': 0 },
    { 'round': 1, 'name': 'CO', 'score': 20 },
    { 'round': 1, 'name': 'LS', 'score': 10 },
    { 'round': 2, 'name': 'JD', 'score': 20 },
    { 'round': 2, 'name': 'YE', 'score': 30 },
    { 'round': 2, 'name': 'HW', 'score': 10 },
    { 'round': 2, 'name': 'CO', 'score': 5 },
    { 'round': 2, 'name': 'LS', 'score': 0 },
    { 'round': 3, 'name': 'JD', 'score': 20 },
    { 'round': 3, 'name': 'YE', 'score': 20 },
    { 'round': 3, 'name': 'HW', 'score': 10 },
    { 'round': 3, 'name': 'CO', 'score': 5 },
    { 'round': 3, 'name': 'LS', 'score': 0 },
    { 'round': 4, 'name': 'JD', 'score': -10 },
    { 'round': 4, 'name': 'YE', 'score': 20 },
    { 'round': 4, 'name': 'HW', 'score': -10 },
    { 'round': 4, 'name': 'CO', 'score': 10 },
    { 'round': 4, 'name': 'LS', 'score': 10 }
]